{
 "title": "Benchmark - Camunda 7",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average PI/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(pi_completed_total{job=\"spring-boot-camunda7\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rates [m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(pi_started_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "PI Started"
    },
    {
     "expr": "rate(pi_backpressure_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "PI Backpressure"
    },
    {
     "expr": "rate(jobs_completed_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "Jobs Completed"
    },
    {
     "expr": "rate(pi_completed_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "PI Completed"
    },
    {
     "expr": "rate(jobs_completed_total{job=\"spring-boot-camunda7\"}[1m]) / rate(pi_started_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "Task/PI Ratio"
    }
   ]
  },
  {
   "title": "Average cycle time in s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pi_cycletime_seconds_sum{job=\"spring-boot-camunda7\"} / pi_cycletime_seconds_count{job=\"spring-boot-camunda7\"}"
    }
   ]
  },
  {
   "title": "Cycle time in ms [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "rate(pi_cycletime_seconds_sum{job=\"spring-boot-camunda7\"}[1m]) / rate(pi_cycletime_seconds_count{job=\"spring-boot-camunda7\"}[1m]) * 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Jobs / PI Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jobs_completed_total{job=\"spring-boot-camunda7\"}[1m]) / rate(pi_started_total{job=\"spring-boot-camunda7\"}[1m])"
    }
   ]
  },
  {
   "title": "PI Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "pi_exception_total{job=\"spring-boot-camunda7\"}",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Jobs Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "jobs_exception_total{job=\"spring-boot-camunda7\"}",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Started PI in total in range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pi_started_total{job=\"spring-boot-camunda7\"})",
     "legendFormat": "PI"
    },
    {
     "expr": "sum(pi_exception_total{job=\"spring-boot-camunda7\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Cycle time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "pi_cycletime_seconds{job=\"spring-boot-camunda7\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Spring Executor Completed Tasks [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total{job=\"spring-boot-camunda7\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}